### ISSUE TITLE
Add STATUS as color to dams layer

### ISSUE THREAD

**Issue by davidheyman** [axismaps/thirdpole#24]
Categorical color scheme (not ordinal)

**Comment by bcsheesley** [comment]
@davidheyman this is done and uploaded but there are a few things to note about the data:
1. There are two datasources in this layer. The Dam Hotspots data includes STATUS but the Global dataset does not. I went ahead and classed all of the global dams with any hotspot dams whose status was "Unknown", so there's a lot of gray on the map.
2. As far as I can tell, this is a 5-class map for our area of extent:
3. Planned: #80b1d3 (blue)
4. Under Construction: #fdb462 (orange)
5. Operational: #b3d369 (green)
6. Suspended: #fb8072 (red)
7. Unknown: #ddd (gray)

There are five or so other classes that I styled, but those dams fall primarily in South America, so I don't think they need to be included in the legend.
