### ISSUE TITLE
Add forest change units to legend

### ISSUE THREAD

**Issue by davidheyman** [axismaps/thirdpole#28]

**Comment by bcsheesley** [comment]
https://www.arcgis.com/home/item.html?id=93ecbfa0542c42fdaa8454fa42a6cc27

Looks like it can be either "density of loss" or "concentration of tree cover loss"

**Comment by davidheyman** [comment]
Can you send me the classification you used in the new color scheme? The values represent years (minus 2000). I think you've used 4 classes but I can't be 100% certain.

**Comment by bcsheesley** [comment]
I just uploaded some new tiles. Here's the classification:

2000-2002 (#f2f0f7)
2003-2005 (#cbc9e2)
2006-2008 (#9e9ac8)
2009-2011 (#756bb1)
2012-2013 (#54278f)
