### ISSUE TITLE
New colors for Cryosphere and Water Cycle legend swatches

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/thirdpole#31]
Cryosphere:
Glacial Lakes: #3b9eb7
Glaciers: #7ee3ea

Water Cycle:
Glaciers: #7ee3ea

**Comment by bcsheesley** [comment]
Scratch that last comment. I changed the snow color, which of course, meant glaciers and glacial lakes had to change  again. Here's the new set:

SNOW
#c1c14d8

GLACIERS
#98d8e2

GLACIAL LAKES
#3d9eb8

**Comment by bcsheesley** [comment]
GLACIAL LAKES had to go darker because of the accentuated shaded relief. It's now: #2d6c89. The others remain the same.

**Comment by davidheyman** [comment]
@bcsheesley Looks like there's an extra digit in Glaciers. Can you send the specs again?

**Comment by bcsheesley** [comment]
Whoops, sorry. Here you go:

Snow: #c1c4d8
Glaciers: #98d8e2
Glacial Lakes: #2d6c89
